main_51_sonarLint-Fix BackEnd
Oral-Cavity-Research/OCR-Spring-Backend pull request #124
Opened 2024-08-11 05:30 UTC by janithkw

(Needs review)

2024-08-11 07:08 UTC, AchinthaHarshamal requested changes

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/controller/Controller.java
>  //    }
remove this comments

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/controller/Controller.java
> +//        return imageService.allImageDetails();
remove unnecessary comments

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/controller/Controller.java
>  //    @PostMapping("/signup")
remove

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/controller/UserController.java
> +    public ResponseEntity<?> updateUserDetail(String id, @RequestBody UserDto userBody) {////////////////////////////need to get id part through authentication
add as TODO:

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/dto/ImageRequestDto.java
> +    private String clinicalDiagnosis;
check this again

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/dto/ImageRequestDto.java
> +    private Boolean lesionsAppear;
check this again

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/dto/PatientDetailsDto.java
> +package com.oasis.ocrspring.dto;
why there is a new class..

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/dto/PatientTeleconResponse.java
> +package com.oasis.ocrspring.dto;
why there is a new class

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/dto/ReportsRequestDto.java
>      @JsonProperty("telecon_entry_id")
check need of JsonProperty

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/repository/RequestRepository.java
>  //    Optional<Request> findByRegNo(String regNo);
remove this

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/service/ImageService.java
> +        List<String> imageIds_ = new ArrayList<>();
why there is _

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/service/ResponseMessages/ErrorResponse.java
>      // Getters and setters
irrelevant comment

2024-08-11 07:08 UTC, AchinthaHarshamal commented on ocrspring/src/main/java/com/oasis/ocrspring/service/TeleconEntriesService.java
> +            Patient patient = patientService.findPatient(patientId, clinicianId);//patient_id, String clinician_id
remove this

2024-08-13 07:27 UTC, janithkw commented on ocrspring/src/main/java/com/oasis/ocrspring/dto/PatientDetailsDto.java
> +package com.oasis.ocrspring.dto;
This is later to be used according to others

2024-08-13 07:27 UTC, janithkw commented on ocrspring/src/main/java/com/oasis/ocrspring/dto/PatientTeleconResponse.java
> +package com.oasis.ocrspring.dto;
Later to be used

2024-08-13 08:58 UTC, merged